name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Verify Assets
      run: make test

    - name: Build Image
      run: make build

    - name: Verify Build
      run: make dgoss
