name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Verify Assets
      run: make test

    - name: Build Image
      run: make build

    - name: Verify Build
      run: make dgoss

    - name: Send mail
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: ${{ github.job }} job of ${{ github.repository }} failed
        body: |
          ${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} failed.
          https://github.com/rmartin16/qbittorrent-api/actions/runs/${{ github.run_id }}
        to: rmartin16+github-action@gmail.com   # comma-separated string
        from: rmartin16+github-action@gmail.com
